server {
    listen 80;
    listen [::]:80;

    server_name www.gistar.com.py gistar.com.py;

    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    root /var/www/html/web;

    index index.html;

    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robots.txt { log_not_found off; access_log off; allow all; }
    location ~* \.(css|gif|ico|jpeg|jpg|js|png)$ {
        expires max;
        log_not_found off;
    }

    # Regla para la descarga del reglamento
    location = /reglamento {
        try_files /files/reglamento.pdf =404;
        default_type application/pdf;
        add_header Content-Disposition 'attachment; filename="reglamento.pdf"';
    }

    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }

    location /css {
        alias /var/www/html/web/css;
    }

    location /js {
        alias /var/www/html/web/js;
    }

    location /img {
        alias /var/www/html/web/img;
    }

    location ~ /\.ht {
        deny all;
    }
}
